<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ProcessTreeFixture</AssemblyName>
    <RootNamespace>Scada.SecurityTests.Fixtures.ProcessTreeFixture</RootNamespace>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
